{
 "panels": [
  {
   "title": "Anomalies détectées",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, anomaly::int AS anomaly FROM weather ORDER BY time;"
    }
   ]
  },
  {
   "title": "Vent",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, wind_speed FROM weather ORDER BY time;"
    }
   ]
  },
  {
   "title": "Température en temps réel",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, temp FROM weather ORDER BY time;"
    }
   ]
  },
  {
   "title": "Humidité & Pression",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, humidity FROM weather ORDER BY time;"
    },
    {
     "rawSql": "SELECT time, pressure FROM weather ORDER BY time;"
    }
   ]
  }
 ]
}